be-02 add
42organization/42gg-onboarding-be-02 pull request #10
Opened 2024-02-04 06:55 UTC by JayJay-Kay

good

2024-02-04 06:57 UTC, JayJay-Kay commented
.DS_Store 얘네들 pr에서 삭제 못해요?

2024-02-05 01:40 UTC, AreSain commented on src/main/java/com/example/board_crud/entity/BoardEntity.java
> +    @Column(length = 20, nullable = false) // 크기 20, ㅜㅐㅅ ㅜㅕㅣㅣ
오타있어요 :)

2024-02-05 01:40 UTC, AreSain commented on src/main/java/com/example/board_crud/service/BoardService.java
> +//DTO -> Entity (Entity Class0
괄호 없어요 :)

2024-02-05 01:54 UTC, AreSain reviewed
코드 잘 봤습니다 :) 게시판에 DB항목이 많아서 엄청 확장되어 있었는데, 오타 수정 및 DTO 랑 Entity 확인 해보시면 좋을 것 같아요!

2024-02-05 01:54 UTC, AreSain commented on src/main/java/com/example/board_crud/entity/BoardEntity.java
> +
엔티티와 테이블은 일치해야하니까 함수를 나눠놓는 것 보다는 하나로 하시되, 새로 만드는 경우 hit을 0을 받는 경우로 바꾸는게 좋아보입니다 :)

2024-02-05 02:45 UTC, yes-ee reviewed
각 기능 별 html 파일까지 직접 만드신 게 인상 깊습니다!
과제 하느라 수고 많으셨어요

2024-02-05 02:45 UTC, yes-ee commented on src/README.md
최상위 폴더명 인트라이름으로 수정 부탁드립니다!

2024-02-05 03:40 UTC, ghyen commented on src/main/java/com/example/board_crud/entity/BoardEntity.java
> +    public static BoardEntity toSaveEntity(BoardDTO boardDTO) {
toSaveEntity, toUpdateEntity를 그냥 BoardEntity생성자로 대체하는 방법도 있을 것 같습니다 그러면 코드 중복이 줄어들 것 같아요~!

2024-02-05 03:52 UTC, ghyen commented on src/main/java/com/example/board_crud/entity/BaseEntity.java
> +public class BaseEntity {
해당 클래스가 언제 어떻게 초기화 되는지 잘 모르겠습니다.. 위에
@EntityListeners(AuditingEntityListener.class) 어노테이션의 기능도 잘 이해가 안가요

2024-02-05 03:52 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/entity/BaseEntity.java
> +public class BaseEntity {
넵 찾아보고 알려드릴게요

2024-02-05 03:57 UTC, ghyen commented on src/main/java/com/example/board_crud/repository/BoardRepository.java
> +    @Query(value = "update BoardEntity b set b.boardHits = b.boardHits + 1 where b.id = :id")
이거는 jQuery인가요?? 어떻게 작동하는건가요?

2024-02-05 03:59 UTC, ghyen commented on src/main/resources/templates/update.html
> +    const boardUpdate = () => {
이게 람다식인가요?? 멋진데요? 코드 설명 부탁드려요

2024-02-05 04:03 UTC, ghyen commented on src/main/java/com/example/board_crud/service/BoardService.java
> +    @Transactional
처음보는 어노테이션입니다. 찾아보니 롤백하기 위한 용도이군요 좋은데요?

2024-02-05 04:06 UTC, ghyen requested changes
예슬님 말대로 인트라 수정 후 머지 하면 될 것 같습니다.

2024-02-05 04:09 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/entity/BoardEntity.java
> +
합쳤습니다

2024-02-05 04:10 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/entity/BoardEntity.java
> +    @Column(length = 20, nullable = false) // 크기 20, ㅜㅐㅅ ㅜㅕㅣㅣ
해결했습니돠~

2024-02-05 05:17 UTC, AreSain approved these changes
질문 마저 해결하시면 될 것 같습니다 :)

2024-02-05 05:19 UTC, yes-ee approved these changes

2024-02-05 06:07 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/repository/BoardRepository.java
> +    @Query(value = "update BoardEntity b set b.boardHits = b.boardHits + 1 where b.id = :id")
jQuery가 아니고 그냥 Query입니다. 저는 게시글에 조회수 기능이 있어서 특정 id에 대해 entity의 boardHit(조회수)을 1 증가시키기 위해 이렇게 JPQL업데이트하는 식으로 짰어요.

2024-02-05 06:29 UTC, JayJay-Kay commented on src/main/resources/templates/update.html
> +    const boardUpdate = () => {
람다식 맞습니다. "(매개변수) => {내용}" 방식으로 이용해서 함수 만듭니다. 간편하긴 한데 아마 생성자로 이용 못하고 몇몇 제약이 있을겁니다.

2024-02-05 06:29 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/service/BoardService.java
> +    @Transactional
감삼돠, 찾아보니 네트워크 문제나 접속자 많을때 안정적으로 관리 (저 같은 경우 조회수 업데이트)할려면 @Transactional 쓰는게 좋다고 하더라고요. 굿~

2024-02-05 06:55 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/entity/BoardEntity.java
> +    public static BoardEntity toSaveEntity(BoardDTO boardDTO) {
그래서 if else문 써서 하나로 합쳤습니다~ 굿~

2024-02-05 07:19 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/entity/BaseEntity.java
> +public class BaseEntity {
@EntityListeners(AuditingEntityListener.class) 기능이 (게시글)작성시간과 업데이트/수정시간 필드를 자동으로 업데이트하기 위해 사용하는겁니다.

2024-02-05 07:19 UTC, JayJay-Kay commented on src/main/java/com/example/board_crud/repository/BoardRepository.java
> +    @Query(value = "update BoardEntity b set b.boardHits = b.boardHits + 1 where b.id = :id")
gpt는 query로 따로 빼면 나중에 수정하기도 쉽고 가독성도 높다고 하네요?

2024-02-05 07:41 UTC, ghyen approved these changes
덕분에 쿼리 어노테이션 알아갑니다 쓸 곳이 정말 많을 것 같아요 진짜로

2024-02-05 07:42 UTC, merged